export const AdminSideNavMenu = [
  {
    id: 1,
    imgBlack: '/assets/admin/sidenav/overview-icon.svg',
    imgColor: '/assets/admin/sidenav/overview-color-icon.svg',
    name: 'Overview',
    alt: '/',
  },
  {
    id: 2,
    imgBlack: '/assets/admin/sidenav/pilla-users-icon.svg',
    imgColor: '/assets/admin/sidenav/pilla-users-color-icon.svg',
    name: 'Pilla Users',
    alt: 'pilla-users',
  },
  {
    id: 3,
    imgBlack: '/assets/admin/sidenav/transactions-icon.svg',
    imgColor: '/assets/admin/sidenav/transactions-color-icon.svg',
    name: 'Transactions',
    alt: 'transactions',
  },
  {
    id: 4,
    imgBlack: '/assets/admin/sidenav/pilla-finance-icon.svg',
    imgColor: '/assets/admin/sidenav/pilla-finance-color-icon.svg',
    name: 'Pilla Finance',
    alt: 'pilla-finance',
  },
  {
    id: 5,
    imgBlack: '/assets/admin/sidenav/savings-icon.svg',
    imgColor: '/assets/admin/sidenav/savings-color-icon.svg',
    name: 'Savings',
    alt: 'savings',
  },
  {
    id: 6,
    imgBlack: '/assets/admin/sidenav/investment-icon.svg',
    imgColor: '/assets/admin/sidenav/investment-color-icon.svg',
    name: 'Investment',
    alt: 'investment',
  },
  {
    id: 7,
    imgBlack: '/assets/admin/sidenav/website-icon.svg',
    imgColor: '/assets/admin/sidenav/website-color-icon.svg',
    name: 'Website',
    alt: 'website',
  },
  {
    id: 8,
    imgBlack: '/assets/admin/sidenav/roles-icon.svg',
    imgColor: '/assets/admin/sidenav/roles-color-icon.svg',
    name: 'Roles',
    alt: 'roles',
  },
  {
    id: 9,
    imgBlack: '/assets/business-dashboard/sidenav/settings-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/settings-color-icon.svg',
    name: 'Settings',
    alt: 'settings',
  },
];
