export const businessSideNavMenu = [
  {
    id: 1,
    imgBlack: '/assets/business-dashboard/sidenav/get-started-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/get-started-color-icon.svg',
    name: 'Get Started',
    alt: '/',
  },
  {
    id: 2,
    imgBlack: '/assets/business-dashboard/sidenav/verification-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/verification-color-icon.svg',
    name: 'Verification',
    alt: 'verification',
  },
  {
    id: 3,
    imgBlack: '/assets/business-dashboard/sidenav/dashboard-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/dashboard-color-icon.svg',
    name: 'Dashboard',
    alt: 'dashboard',
  },
  {
    id: 4,
    imgBlack: '/assets/business-dashboard/sidenav/payment-link-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/payment-link-color-icon.svg',
    name: 'Payment Link',
    alt: 'payment-link',
  },
  {
    id: 5,
    imgBlack: '/assets/business-dashboard/sidenav/api-and-webhook-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/api-and-webhook-color-icon.svg',
    name: 'API & Webhook',
    alt: 'api-and-webhook',
  },
  {
    id: 6,
    imgBlack: '/assets/business-dashboard/sidenav/pilla-savings-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/pilla-savings-color-icon.svg',
    name: 'Pilla Savings',
    alt: 'pilla-savings',
  },
  {
    id: 7,
    imgBlack: '/assets/business-dashboard/sidenav/pilla-investment-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/pilla-investment-color-icon.svg',
    name: 'Pilla Investment',
    alt: 'pilla-invest',
  },
  {
    id: 8,
    imgBlack: '/assets/business-dashboard/sidenav/pilla-construction-finance-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/pilla-construction-finance-color-icon.svg',
    name: 'Pilla construction Finance',
    alt: 'pilla-construction-finance',
  },
  {
    id: 9,
    imgBlack: '/assets/business-dashboard/sidenav/refer-and-earn-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/refer-and-earn-color-icon.svg',
    name: 'Refer-and-Earn',
    alt: 'refer-and-earn',
  },
  {
    id: 10,
    imgBlack: '/assets/business-dashboard/sidenav/support-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/support-color-icon.svg',
    name: 'Support',
    alt: 'support',
  },
  {
    id: 11,
    imgBlack: '/assets/business-dashboard/sidenav/settings-icon.svg',
    imgColor: '/assets/business-dashboard/sidenav/settings-color-icon.svg',
    name: 'Settings',
    alt: 'settings',
  },
];
